import type { Metadata } from "next";
import localFont from 'next/font/local'
import ApolloProvider from "@/components/common/ApolloProvider";
import "./globals.css";

const accordAlt = localFont({
  src: [
    {
      path: './AccordAltReg.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './AccordAltBold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={accordAlt.className}>
        <ApolloProvider>
          {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
